version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "echo", "Skip backend service in local override" ]
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - skillhub-network
    restart: "no"
