version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: skillhub-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: skillhub
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - skillhub-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillhub-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - postgres
    networks:
      - skillhub-network

volumes:
  postgres-data:

networks:
  skillhub-network:
    driver: bridge
